### ISSUE TITLE
example is not working when running npm run webpack

### ISSUE THREAD

**Issue by kkho** [graphql-dotnet/examples#1]
Gets an error when running npm run webpack:

>  Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/graphiql/graphiql.css:
>            2 modules
>     Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!app/app.css:
>            [0] ./node_modules/css-loader!./app/app.css 295 bytes {0} [built]
>             + 1 hidden module
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! gql-example@1.0.0 webpack: `webpack --progress`
> npm ERR! Exit status 2
> npm ERR!
> npm ERR! Failed at the gql-example@1.0.0 webpack script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\kim\AppData\Roaming\npm-cache\_logs\2018-06-15T09_28_46_207Z-debug.log

need to add this in package.json inside the "dependencies" prop:     "graphql": "^0.13.2",

**Comment by joemcbride** [comment]
Can you provide which sample you got this error with and what versions of node and npm you’re using?

**Comment by DanielCauser** [comment]
I have had this issue when trying to run the command `npm run webpack`

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'webpack' ]
2 info using npm@6.1.0
3 info using node@v10.4.1
4 verbose run-script [ 'prewebpack', 'webpack', 'postwebpack' ]
5 info lifecycle gql-example@1.0.0~prewebpack: gql-example@1.0.0
6 info lifecycle gql-example@1.0.0~webpack: gql-example@1.0.0
7 verbose lifecycle gql-example@1.0.0~webpack: unsafe-perm in lifecycle true
8 verbose lifecycle gql-example@1.0.0~webpack: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\examples\src\AspNetCoreCustom\node_modules\.bin;C:\Program Files (x86)\Parallels\Parallels Tools\Applications;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Users\danielcauser\AppData\Local\Microsoft\WindowsApps;C:\Users\danielcauser\AppData\Local\GitHubDesktop\bin;C:\Program Files\Microsoft VS Code\bin;C:\Users\danielcauser\AppData\Local\Microsoft\WindowsApps;C:\Users\danielcauser\AppData\Roaming\npm
9 verbose lifecycle gql-example@1.0.0~webpack: CWD: C:\examples\src\AspNetCoreCustom
10 silly lifecycle gql-example@1.0.0~webpack: Args: [ '/d /s /c', 'webpack --progress' ]
11 silly lifecycle gql-example@1.0.0~webpack: Returned: code: 2  signal: null
12 info lifecycle gql-example@1.0.0~webpack: Failed to exec webpack script
13 verbose stack Error: gql-example@1.0.0 webpack: `webpack --progress`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
14 verbose pkgid gql-example@1.0.0
15 verbose cwd C:\examples\src\AspNetCoreCustom\Example
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "webpack"
18 verbose node v10.4.1
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 2
22 error gql-example@1.0.0 webpack: `webpack --progress`
22 error Exit status 2
23 error Failed at the gql-example@1.0.0 webpack script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by kkho** [comment]
sorry for late reply @joemcbride . I have node version 8.11.3 and npm version: 5.6.0 (should be updated to the latest I guess).

I ran tjhe AspNetWebApi project.

Then again, it seems to solve this problem, is to install "graphql": "^0.13.2",

"npm install graphql"

**Comment by DanielCauser** [comment]
I'm going to try that @kkho I will post my results here.

**Comment by joemcbride** [comment]
This should be fixed on master now.  Sorry about that!

**Comment by DanielCauser** [comment]
It worked for me!!

**Comment by DanielCauser** [comment]
@joemcbride I'm really interested in this, do you have any resources to point where I could read and learn more about how this is all working??

**Comment by joemcbride** [comment]
@DanielCauser here’s a great blog series that goes over the basics if that’s what you’re looking for?

http://fiyazhasan.me/tag/graphql-dotnet/
