### ISSUE TITLE
Cannot retrieve schema but queries work in prototype

### ISSUE THREAD

**Issue by jhensley707** [graphql-dotnet/examples#11]
I downloaded the example app and it works properly, submitting queries and manipulations and viewing the schema. I then created my own prototype following the example app framework with a new AspNetCore web api and my own types. When I run my prototype, the UI Playground works to submit queries and mutations against my service (and I can put a breakpoint in the service and manipulate the return result values). However, there is no schema displayed in the viewer of the UI Playground. I'm not getting any error messages and I can't determine if this is an error in the Playground client app or if this is an issue in my prototype service. What can I do to identify the cause of this behavior?

**Comment by joemcbride** [comment]
Hey, hopefully you were able to move past your issue.  If not, I'm not sure how I can help with this other than if you push up a repo that demonstrates the issue I can try to track it down.  First thing I would look at is if there are conflicts with the version of GraphiQL npm package and the GraphQL .NET nuget.

What versions of those packages are you using?

**Comment by jhensley707** [comment]
I uploaded my proto project here: https://github.com/jhensley707/graphql-aspnetcore-proto

I have not updated it since I first created it. Here are the package versions:
    <PackageReference Include="GraphQL" Version="2.4.0" />
    <PackageReference Include="GraphQL.Server.Core" Version="3.2.0" />
    <PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="3.2.0" />
    <PackageReference Include="GraphQL.Server.Ui.Playground" Version="3.2.0" />

**Comment by sungam3r** [comment]
@jhensley707 It is possibly fixed by #25. The latest versions of packages were taken and compatibility errors were fixed.

**Comment by sungam3r** [comment]
@jhensley707 #25 was merged. Also all aforementioned packages changed their current versions. Is this issue still actual?

**Comment by sungam3r** [comment]
Closed due to lack of feedback.
