### ISSUE TITLE
Updated Nugets to 2.2 and Version 3 preview - error in Middleware

### ISSUE THREAD

**Issue by richardkeller411** [graphql-dotnet/examples#13]
Getting this error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0266	Cannot implicitly convert type 'object' to 'System.Collections.Generic.IDictionary<string, object>'. An explicit conversion exists (are you missing a cast?)	 GraphQLMiddleware.cs	 Line 62

**Comment by joemcbride** [comment]
`UserContext` changed from type `object` to type `IDictionary<string, object>` from 2.x to 3.x.

**Comment by sungam3r** [comment]
Examples were updated to reflect all changes.
