### ISSUE TITLE
Error finding csc.exe and proposed fix

### ISSUE THREAD

**Issue by pmeijer** [graphql-dotnet/examples#19]
https://stackoverflow.com/questions/32780315/could-not-find-a-part-of-the-path-bin-roslyn-csc-exe

**Comment by joemcbride** [comment]
Hey, this would be an issue with your environment and not with this project.  The webapi project is designed to work with Visual Studio.  The other projects use dotnet core.

**Comment by pmeijer** [comment]
Right, just posted it here in case anyone else runs into the same issue.
