### ISSUE TITLE
Issue running the sample

### ISSUE THREAD

**Issue by DanielCauser** [graphql-dotnet/examples#2]
Hey! I forked this sample repo but when I run the API project the browser comes up with a blank screen.

I just started studying GraphQL and I would very much like to see a working API sample.

**Comment by joemcbride** [comment]
The Web API project?  Did you follow the instructions in the readme?

**Comment by DanielCauser** [comment]
I did not have node.js installed in my machine. Now I think I can make this work!

**Comment by DanielCauser** [comment]
Almost, I'm facing the same issue reported #1 now :(
