### ISSUE TITLE
AddUserContextBuilder error in .NET core 3.0

### ISSUE THREAD

**Issue by Jjaszkowiak** [graphql-dotnet/examples#23]
While attempting to update our application from .NET core 2.2 to 3.0 we got the following error:

The type 'xyz.Service.GraphQLUserContext' cannot be used as type parameter 'TUserContext' in the generic type or method 'GraphQLBuilderExtensions.AddUserContextBuilder<TUserContext>(IGraphQLBuilder, Func<HttpContext, TUserContext>)'. There is no implicit reference conversion from 'xyz.Service.GraphQLUserContext' to 'System.Collections.Generic.IDictionary<string, object>'.	

While attempting the following code:

            services.AddGraphQL(_ =>
            {
                _.EnableMetrics = true;
                _.ExposeExceptions = true;
            })
            .AddUserContextBuilder(httpContext => new GraphQLUserContext { User = httpContext.User })
            .AddWebSockets(); // Add required services for web socket support;

**Comment by joemcbride** [comment]
This is a breaking change in 3.0.  The `UserContext` now needs to be of type `Dictionary<string, object>`.  The simplest solution is to have your existing `GraphQLUserContext` implement that interface.

```csharp
public class GraphQLUserContext : Dictionary<string, object>
{
}
```

If that does not work for your scenario, you can instead just set that to a dictionary and add your existing context class as a value in the dictionary.

```csharp
.AddUserContextBuilder(httpContext => {
  var myContext = new GraphQLUserContext { User = httpContext.User };
  var dictionary = new Dictionary<string, object>();
  dictionary["my_context"] = myContext;
  return dictionary;
})
```

Now you can get your context by fetching it with your `my_context` key.

**Comment by Jjaszkowiak** [comment]
Thanks. That resolved the compile errors. I can't fully test because I am also getting "error": "Unexpected token S in JSON at position 0" in the playground but I think this error at least is resolved.

**Comment by sungam3r** [comment]
Examples were updated to reflect all changes.
