### ISSUE TITLE
Unamapped Selection

### ISSUE THREAD

**Issue by Shubhankar-Nath** [graphql-dotnet/examples#24]
![image](https://user-images.githubusercontent.com/25512363/63426884-84163400-c431-11e9-9cd1-0437a9c33ad7.png)

I am getting while running this project. I just made one change to add a source o visual studio to look for GraphQL Package.

Also any project I try to run on GraphQl I am getting the same error.

**Comment by sungam3r** [comment]
You should use valid query. Droid field has argument and should have selection set.
This is an example of a valid query:
```
{
  droid(id: "3")
  {
    id
    name
  }
}
```

**Comment by sungam3r** [comment]
Also see updated examples - #25

**Comment by sungam3r** [comment]
#25 has been merged in master
