### ISSUE TITLE
how to use Variables?

### ISSUE THREAD

**Issue by txeagle** [graphql-dotnet/examples#26]
how to get Variables in resolve?

**Comment by sungam3r** [comment]
`ResolveFieldContext.Variables` or if you mean arguments: `ResolveFieldContext.GetArgument<string>("id")`

**Comment by txeagle** [comment]
resolve: context =>
                {
                    var human = context.GetArgument<Human>("human");
                    return data.AddHuman(human);
                });


{"query":"mutation {createHuman(human:{name:\"newName\"}) {id name}}","variables":{"testvariable":"newhome"}}
just like demo code,
i can get agrument use 'var human = context.GetArgument<Human>("human");'
but how can i get testvariable's value?

**Comment by sungam3r** [comment]
`ResolveFieldContext.Variables.ValueFor("testvariable")`

**Comment by sungam3r** [comment]
@txeagle Is this question still actual?

**Comment by sungam3r** [comment]
Closed due to lack of feedback.
