### ISSUE TITLE
Is it possible to use two schema?

### ISSUE THREAD

**Issue by txeagle** [graphql-dotnet/examples#27]
private ISimpleContainer BuildContainer()
        {
            var container = new SimpleContainer();
            container.Singleton<IDocumentExecuter>(new DocumentExecuter());
            container.Singleton<IDocumentWriter>(new DocumentWriter(true));

            container.Register<EmphQuery>();
            container.Register<EmphMutation>();
            container.Register<EmphType>();
            container.Singleton<ISchema>(new EmphSchema(new FuncDependencyResolver(type => container.Get(type))));

            container.Register<DeptQuery>();
            container.Register<DeptType>();
            **container.Singleton<ISchema>(new DeptSchema(new FuncDependencyResolver(type => container.Get(type))));**

            return container;
        }

it throw an exception:
System.ArgumentException:“ An item with the same key has already been added

if i modify to:
container.Singleton<**DeptSchema**>(new DeptSchema(new FuncDependencyResolver(type => container.Get(type))));
it seems Invalid when i query dept

**Comment by sungam3r** [comment]
You can use different schemas in different di container instances.

**Comment by sungam3r** [comment]
@txeagle Yes, it is possible even in single container. See graphql-dotnet/graphql-dotnet#1154.
Relates to #30 .
