### ISSUE TITLE
Example using subscriptions with ASP.NET Web API

### ISSUE THREAD

**Issue by corstian** [graphql-dotnet/examples#3]
Are there any examples/resources available on the topic of using subscriptions with ASP.NET Web API?

While creating a model for subscriptions is not a problem, connecting it with a transport layer seems to be quite a hassle.

**Comment by joemcbride** [comment]
I am not aware of any at present.

**Comment by corstian** [comment]
Ty! In the meantime I worked around the issue by finding a way to be able to use asp core :)
