### ISSUE TITLE
Authentication/Authorization in core 2.2 and core 3.0

### ISSUE THREAD

**Issue by pkellner** [graphql-dotnet/examples#33]
Sorry for cluttering up issues here, but this seems like the place where this is good dialog about this project. I plan on updating my Pluralsight course soon (after core 3.1 ships) on asp.net core and React and I want to include a short section on integration with React using this project. I'm in no hurry to get a good answer, but want to make sure I understand what is a best practice way I should do things. For now, I'm sticking to core 2.2 because I gave up on the develop branch (until it is stable enough for me, my issue, I'm sure it's fine).

So, I've JwtToken's working as I want and in standard controllers, the attributes Authorize and Roles are working correctly and I want similar functionality in GraphQL.  In my "Type" file, for example, I want to only show the email address if the user is authenticated and has a role of admin.  What I've done is modify the Field definition from:

`Field(t => t.Email).Description("users unique email");`

to

```
Field<StringGraphType>("email", resolve: context =>
{
    var isAuthenticated = GetAuthStatus.Get(context.UserContext as ClaimsPrincipal, out var username, out var isAdmin);
    return isAuthenticated && isAdmin ? context.Source.Email + ":" + username : "<email blocked>:" + username;
});
```

And, I've created a simple getAuthStatus class as follows:

```
public static class GetAuthStatus
{
    public static bool Get(ClaimsPrincipal user, out string username, out bool isAdmin)
    {
        var isAuthenticated = ((ClaimsIdentity)user.Identity).IsAuthenticated;
        if (isAuthenticated)
        {
            username = user.Identity.Name;
            isAdmin = ((ClaimsIdentity)user.Identity).Claims.Any(a =>
                a.Type == "http://schemas.microsoft.com/ws/2008/06/identity/claims/role" && a.Value == "Admin");
        }
        else
        {
            username = "";
            isAdmin = false;
        }
        return isAuthenticated;
    }
}
```

My solutions quite clunky. Is there either now (2.2) a hugely better way to do this, or in (3.0/3.1) is there a better way coming?  My goal is to keep the code in the Types themselves as simple as possible.

Thanks

**Comment by sungam3r** [comment]
First you need to answer the question. Do you want to return some default values if the user is not authorized? Or do you want to prevent him from receiving fields as such if user is not authorized? In the first case, you work at the resolver level yourself. In the second case, you can use authorization api: https://github.com/graphql-dotnet/authorization or https://github.com/graphql-dotnet/server/tree/develop/src/Authorization.AspNetCore .

**Comment by pkellner** [comment]
@sungam3r default values are not important so I believe I should be able to use the https://github.com/graphql-dotnet/authorization project.  I'm still lost on master vs develop branches.  I struggled for many hours and finally gave up trying to get the develop branch working in my non-production app, but don't want to create throw away code.  Is there a stable way to include the develop branch code into a standalone visual studio project without building the full project zip and then linking to the project? I'd like to use the newer bits, but not if it's going to cause me a lot of issues I don't understand or can't fix myself. I'm still quite new here.

**Comment by joemcbride** [comment]
@pkellner nugets are published on nuget.org as “preview” versions, so no need to try to use the source.
