### ISSUE TITLE
example code is outdated?

### ISSUE THREAD

**Issue by netcrave** [graphql-dotnet/examples#4]
I can't find a definition for IDocumentExecuter. Using GraphQL 0.17.3 from nuget. I searched through this source tree too and couldn't find it.

**Comment by joemcbride** [comment]
Here is the source for 0.17.3: https://github.com/graphql-dotnet/graphql-dotnet/tree/v0.17.3

That interface is in the `DocumentExecutor.cs` file.

https://github.com/graphql-dotnet/graphql-dotnet/blob/a711816edfd5ad5edc9dc2340d5f23f8f244daaa/src/GraphQL/Execution/DocumentExecuter.cs#L20-L34

These examples use the 2.0 prerelease nuget package.  It exists there too, in the same file.

https://github.com/graphql-dotnet/graphql-dotnet/blob/4e74411859c27c3e44c8b3751abfcb51f2f1adcf/src/GraphQL/Execution/DocumentExecuter.cs#L17-L32

**Comment by netcrave** [comment]
Thanks @joemcbride I was looking for it in the wrong place :)
