### ISSUE TITLE
.net5 example

### ISSUE THREAD

**Issue by zulander1** [graphql-dotnet/examples#52]
Can we get some examples for .net5
Thank you

**Comment by sungam3r** [comment]
Waiting for GraphQL.NET v4

**Comment by develorem** [comment]
We're up to .NET 6 now. Keen to see some server examples for .NET 6, particularly with WebApi.
Its a hassle to work out what to do from existing blog posts and examples as many extension methods are marked as [Obsolete].
Version 4 has been out for some time now..

**Comment by sungam3r** [comment]
I'll try to push net5 and net6 examples this weekend.

**Comment by sungam3r** [comment]
Done. As it turned out, I updated these examples locally very long ago, but did not push them.

**Comment by sungam3r** [comment]
#87
