### ISSUE TITLE
Startup uses obsolete methods

### ISSUE THREAD

**Issue by develorem** [graphql-dotnet/examples#88]
In some examples startup is using obsolete methods. 
There was changes recently to simply add the pragma statement to ignore compiler warnings. Why?
Why not just use the correct methods?
This was also called out in the PR when this was merged only hours ago.
Also it would help if the Obsolete attributes also contained the information indicating which alternatives should be used instead.
I'm still struggling to find the right way to register these components in .NET 6 for a webapi project.

**Comment by Shane32** [comment]
@develorem Please let me know if the updated samples in PR #89 are sufficient or if you feel another sample should be added.

Thanks!

**Comment by develorem** [comment]
@Shane32 Champion, looks good. I'll be trying this in a couple hours from now.
As an aside, I'm reading the online docs around schema and finding the examples in the common 'StarWars' project are quite simplistic in comparison. Would be good to see the schema flushed out with a bit more detail. And some integration tests in the same project that fire off some queries against the API to demonstrate some of the query functionality. Would it make sense for me to log that as a separate issue?

**Comment by develorem** [comment]
@Shane32  Tried the branch code, the queries won't execute from \playground anymore, although its not raising any exceptions for me either. Screen just goes blank.

**Comment by Shane32** [comment]
@develorem It seemed to work for me.  Any errors in the console?  Note that it's `/ui/playground`.

![image](https://user-images.githubusercontent.com/6377684/155916911-0166cebc-ca38-4f79-95f2-b44f72a27ce7.png)

**Comment by Shane32** [comment]
Oh you mentioned a console error. No idea what that is...

We should probably continue discussion of bugs related to this PR in PR #89

**Comment by Shane32** [comment]
> Would be good to see the schema flushed out with a bit more detail. And some integration tests in the same project that fire off some queries against the API to demonstrate some of the query functionality. Would it make sense for me to log that as a separate issue?

Sure, feel free to add separate issues for these topics, and then @sungam3r and I can review and/or respond.
