### ISSUE TITLE
Where is the code for GraphQLQuery?

### ISSUE THREAD

**Issue by jasebanico** [graphql-dotnet/examples#9]
Where is the code for GraphQLQuery?

**Comment by joemcbride** [comment]
If you are referring to the Web API example, that class is here:

https://github.com/graphql-dotnet/examples/blob/master/src/AspNetWebApi/Example/Controllers/GraphQLController.cs#L79

**Comment by sungam3r** [comment]
Now it's [here](https://github.com/graphql-dotnet/examples/blob/master/src/AspNetWebApi/WebApi/Controllers/GraphQLController.cs#L68).
