### ISSUE TITLE
Update examples to v5.0.0.

### ISSUE THREAD

**Issue by Shuttle42** [graphql-dotnet/examples#92]
The examples are using the version 4.7.1 and the latest stable is 5.0.0. I updated my nuget packages and struggling now with diverse issues. Please update at least AppNetCoreController.

**Comment by Shane32** [comment]
See https://github.com/Shane32/GraphQL.AspNetCore3 which includes a controller sample within the readme and a more complete sample here: https://github.com/Shane32/GraphQL.AspNetCore3/tree/master/src/Samples/ControllerSample

**Comment by ktutnik** [comment]
I have created simple project with simplest setup with V5 and Net Core 6

https://github.com/ktutnik/SimpleGraphQLDotNet

**Comment by Shuttle42** [comment]
Thank you @Shane32 and thank you @ktutnik. I was able to upgrade my solution to V5 and it works.
